INSERT INTO `ec_tipos_transferencias` (`id_tipo_transferencia`, `nombre`, `orden`, `listar_en_transferencias`) VALUES ('10', 'Transferencia entre la misma sucursal', '0', '0'), ('11', 'Transferencia a otra sucursal', '0', '0');

INSERT INTO `sys_menus` (`id_menu`, `nombre`, `es_listado`, `tabla_relacionada`, `liga`, `menu_padre`, `en_permisos`, `icono`, `orden`, `no_tabla`, `habilitado`, `enlistado`, `sincronizar`) 
VALUES ('253', '1.26 Ttransferencias desde sucursal', '0',  NULL, 'code/especiales/Transferencias/transferencias_cortas/index.php?', '3', '1', NULL, '26', '6', b'1', '1', '1');

INSERT INTO `sys_menus` (`id_menu`, `nombre`, `es_listado`, `tabla_relacionada`, `liga`, `menu_padre`, `en_permisos`, `icono`, `orden`, `no_tabla`, `habilitado`, `enlistado`, `sincronizar`) 
VALUES ('254', '1.27 Listado de transferencias de la sucursal', '1', 'ec_transferencias', NULL, '3', '1', NULL, '27', '6', b'1', '1', '1');

INSERT INTO `sys_listados` (`id_listado`, `titulo`, `tabla`, `no_tabla`, `consulta`, `anchos`, `alineacion`, `campos`, `ver`, `modificar`, `eliminar`, `condicion`, `nuevo`, `buscador`, `consulta_buscador`, `condiciones_buscador`, `sincronizar`) VALUES
(102, '1.27 Transferencias desde esta sucursal', 'ec_transferencias', 6, 'SELECT\r\nt.id_transferencia AS ID,\r\nt.folio AS Folio,\r\na.nombre AS \'Almacen origen\',\r\na2.nombre AS \'Almacen destino\',\r\nCONCAT(t.fecha, \' \', t.hora) AS \'Fecha y Hora\',\r\ne.nombre AS \'Estatus\',\r\nt.impresa AS \'imprimido\',\r\nCONCAT(\r\n \'TÍTULO : \',\r\n t.titulo_transferencia,\r\n \'\\n\',\r\n \'NOTAS : \',\r\n t.observaciones\r\n)as Observaciones\r\nFROM ec_transferencias t\r\nJOIN ec_almacen a ON t.id_almacen_origen=a.id_almacen\r\nJOIN ec_almacen a2 ON t.id_almacen_destino = a2.id_almacen\r\nJOIN ec_estatus_transferencia e ON t.id_estado = e.id_estatus', '0|120|180|180|100|150|0|0', 'center|center|left|left|center|left|center|enter', 't.id_transferencia|t.folio|a.nombre|a2.nombre|CONCAT(t.fecha, \' \', t.hora)|e.nombre|t.impresa|CONCAT(\r\n \'TÍTULO : \',\r\n t.titulo_transferencia,\r\n \'\\n\',\r\n \'NOTAS : \',\r\n t.observaciones\r\n)', 1, 0, 1, 'AND t.id_transferencia > 0\r\nAND t.id_tipo IN( 10, 11 )\r\nAND IF(\'$SUCURSAL\'=-1,t.id_sucursal_origen>0,(t.id_sucursal_origen=\'$SUCURSAL\' OR t.id_sucursal_destino=\'$SUCURSAL\'))', 1, b'1', 't.folio', NULL, 1);
